// Provisional navigation labels until Localization adds these semantic shell keys.
// Mission, phase, objective and dialog copy always comes from GoblinLanguage.t.
const navigation = {
  de: {
    'ui.start.title': 'G.O.B.L.I.N.', 'ui.start.subtitle': 'Interne modulare Testpartien',
    'ui.start.choose': 'Mission wählen', 'ui.levels.title': 'Verfügbare Testpartien',
    'ui.levels.select': 'Briefing öffnen', 'ui.briefing.start': 'Einsatz beginnen',
    'ui.nav.back': 'Zurück', 'ui.nav.pause': 'Pause', 'ui.nav.resume': 'Spiel fortsetzen',
    'ui.nav.settings': 'Einstellungen', 'ui.nav.help': 'Hilfe', 'ui.nav.missions': 'Missionswahl',
    'ui.nav.restart': 'Mission neu starten', 'ui.nav.close': 'Schließen',
    'ui.hud.turn': 'Zug {turn}', 'ui.hud.ready': '{count} Einheiten bereit',
    'ui.hud.noSelection': 'Keine Einheit gewählt', 'ui.hud.selected': '{unitId} · {hp} HP',
    'ui.hud.intent.move': 'Bewegung nach Feld {x}, {y}', 'ui.hud.intent.fire': 'Feuer auf {targetId}',
    'ui.hud.intent.confirm': 'Befehl ausführen', 'ui.hud.intent.cancel': 'Ziel verwerfen',
    'ui.hud.noIntent': 'Einheit oder Feld wählen', 'ui.hud.blocked': 'Aktion gesperrt: {reason}',
    'ui.hud.phase': 'Phase beenden', 'ui.hud.units': 'Einheiten', 'ui.hud.intel': 'Feldinfo',
    'ui.hud.log': 'Log', 'ui.hud.recenter': 'Zur Auswahl', 'ui.hud.zoomIn': 'Vergrößern',
    'ui.hud.zoomOut': 'Verkleinern', 'ui.hud.grid': 'Hexraster',
    'ui.hud.terrain': 'Terrain-Studie', 'ui.hud.hex': 'Hexkarte', 'ui.hud.style': 'Stilset',
    'ui.hud.overlay.move': 'Bewegung', 'ui.hud.overlay.fire': 'Feuer', 'ui.hud.overlay.sight': 'Sicht',
    'ui.settings.language': 'Sprache', 'ui.settings.terrain': 'Kartendarstellung',
    'ui.settings.style': 'Materialset', 'ui.settings.grid': 'Hexraster',
    'ui.details.units': 'Einheiten', 'ui.details.intel': 'Feld / Einheit', 'ui.details.log': 'Ereignisse',
    'ui.dialog.confirm': 'Bestätigen', 'ui.dialog.cancel': 'Abbrechen',
    'ui.dialog.leaveMission.body': 'Die laufende Mission endet. Bisherige Befehle und Fortschritte gehen verloren. Danach öffnet sich die Missionswahl.',
  },
  en: {
    'ui.start.title': 'G.O.B.L.I.N.', 'ui.start.subtitle': 'Internal modular test games',
    'ui.start.choose': 'Choose mission', 'ui.levels.title': 'Available test games',
    'ui.levels.select': 'Open briefing', 'ui.briefing.start': 'Begin mission',
    'ui.nav.back': 'Back', 'ui.nav.pause': 'Pause', 'ui.nav.resume': 'Resume game',
    'ui.nav.settings': 'Settings', 'ui.nav.help': 'Help', 'ui.nav.missions': 'Mission selection',
    'ui.nav.restart': 'Restart mission', 'ui.nav.close': 'Close',
    'ui.hud.turn': 'Turn {turn}', 'ui.hud.ready': '{count} units ready',
    'ui.hud.noSelection': 'No unit selected', 'ui.hud.selected': '{unitId} · {hp} HP',
    'ui.hud.intent.move': 'Move to cell {x}, {y}', 'ui.hud.intent.fire': 'Fire at {targetId}',
    'ui.hud.intent.confirm': 'Execute order', 'ui.hud.intent.cancel': 'Discard target',
    'ui.hud.noIntent': 'Select a unit or cell', 'ui.hud.blocked': 'Action blocked: {reason}',
    'ui.hud.phase': 'End phase', 'ui.hud.units': 'Units', 'ui.hud.intel': 'Cell info',
    'ui.hud.log': 'Log', 'ui.hud.recenter': 'To selection', 'ui.hud.zoomIn': 'Zoom in',
    'ui.hud.zoomOut': 'Zoom out', 'ui.hud.grid': 'Hex grid',
    'ui.hud.terrain': 'Terrain study', 'ui.hud.hex': 'Hex map', 'ui.hud.style': 'Style set',
    'ui.hud.overlay.move': 'Movement', 'ui.hud.overlay.fire': 'Fire', 'ui.hud.overlay.sight': 'Sight',
    'ui.settings.language': 'Language', 'ui.settings.terrain': 'Map display',
    'ui.settings.style': 'Material set', 'ui.settings.grid': 'Hex grid',
    'ui.details.units': 'Units', 'ui.details.intel': 'Cell / unit', 'ui.details.log': 'Events',
    'ui.dialog.confirm': 'Confirm', 'ui.dialog.cancel': 'Cancel',
    'ui.dialog.leaveMission.body': 'The current mission ends. Orders and progress are lost. Mission selection opens next.',
  },
  es: {
    'ui.start.title': 'G.O.B.L.I.N.', 'ui.start.subtitle': 'Partidas modulares de prueba',
    'ui.start.choose': 'Elegir misión', 'ui.levels.title': 'Partidas de prueba disponibles',
    'ui.levels.select': 'Abrir informe', 'ui.briefing.start': 'Iniciar misión',
    'ui.nav.back': 'Volver', 'ui.nav.pause': 'Pausa', 'ui.nav.resume': 'Continuar partida',
    'ui.nav.settings': 'Ajustes', 'ui.nav.help': 'Ayuda', 'ui.nav.missions': 'Elegir misión',
    'ui.nav.restart': 'Reiniciar misión', 'ui.nav.close': 'Cerrar',
    'ui.hud.turn': 'Turno {turn}', 'ui.hud.ready': '{count} unidades listas',
    'ui.hud.noSelection': 'Ninguna unidad elegida', 'ui.hud.selected': '{unitId} · {hp} PV',
    'ui.hud.intent.move': 'Mover a casilla {x}, {y}', 'ui.hud.intent.fire': 'Disparar a {targetId}',
    'ui.hud.intent.confirm': 'Ejecutar orden', 'ui.hud.intent.cancel': 'Descartar objetivo',
    'ui.hud.noIntent': 'Elige una unidad o casilla', 'ui.hud.blocked': 'Acción bloqueada: {reason}',
    'ui.hud.phase': 'Terminar fase', 'ui.hud.units': 'Unidades', 'ui.hud.intel': 'Casilla',
    'ui.hud.log': 'Registro', 'ui.hud.recenter': 'Ir a selección', 'ui.hud.zoomIn': 'Acercar',
    'ui.hud.zoomOut': 'Alejar', 'ui.hud.grid': 'Cuadrícula',
    'ui.hud.terrain': 'Estudio del terreno', 'ui.hud.hex': 'Mapa hexagonal', 'ui.hud.style': 'Estilo',
    'ui.hud.overlay.move': 'Movimiento', 'ui.hud.overlay.fire': 'Fuego', 'ui.hud.overlay.sight': 'Vista',
    'ui.settings.language': 'Idioma', 'ui.settings.terrain': 'Vista del mapa',
    'ui.settings.style': 'Material', 'ui.settings.grid': 'Cuadrícula',
    'ui.details.units': 'Unidades', 'ui.details.intel': 'Casilla / unidad', 'ui.details.log': 'Eventos',
    'ui.dialog.confirm': 'Confirmar', 'ui.dialog.cancel': 'Cancelar',
    'ui.dialog.leaveMission.body': 'La misión actual termina. Se pierden las órdenes y el progreso. Después se abre la selección de misiones.',
  },
  fr: {
    'ui.start.title': 'G.O.B.L.I.N.', 'ui.start.subtitle': 'Parties modulaires de test',
    'ui.start.choose': 'Choisir une mission', 'ui.levels.title': 'Parties de test disponibles',
    'ui.levels.select': 'Ouvrir le briefing', 'ui.briefing.start': 'Commencer la mission',
    'ui.nav.back': 'Retour', 'ui.nav.pause': 'Pause', 'ui.nav.resume': 'Reprendre la partie',
    'ui.nav.settings': 'Paramètres', 'ui.nav.help': 'Aide', 'ui.nav.missions': 'Choix de mission',
    'ui.nav.restart': 'Recommencer la mission', 'ui.nav.close': 'Fermer',
    'ui.hud.turn': 'Tour {turn}', 'ui.hud.ready': '{count} unités prêtes',
    'ui.hud.noSelection': 'Aucune unité sélectionnée', 'ui.hud.selected': '{unitId} · {hp} PV',
    'ui.hud.intent.move': 'Déplacer vers la case {x}, {y}', 'ui.hud.intent.fire': 'Tirer sur {targetId}',
    'ui.hud.intent.confirm': 'Exécuter l’ordre', 'ui.hud.intent.cancel': 'Annuler la cible',
    'ui.hud.noIntent': 'Choisissez une unité ou une case', 'ui.hud.blocked': 'Action bloquée : {reason}',
    'ui.hud.phase': 'Terminer la phase', 'ui.hud.units': 'Unités', 'ui.hud.intel': 'Case',
    'ui.hud.log': 'Journal', 'ui.hud.recenter': 'Vers la sélection', 'ui.hud.zoomIn': 'Agrandir',
    'ui.hud.zoomOut': 'Réduire', 'ui.hud.grid': 'Grille hexagonale',
    'ui.hud.terrain': 'Étude du terrain', 'ui.hud.hex': 'Carte hexagonale', 'ui.hud.style': 'Style',
    'ui.hud.overlay.move': 'Déplacement', 'ui.hud.overlay.fire': 'Tir', 'ui.hud.overlay.sight': 'Vue',
    'ui.settings.language': 'Langue', 'ui.settings.terrain': 'Affichage de la carte',
    'ui.settings.style': 'Matériau', 'ui.settings.grid': 'Grille hexagonale',
    'ui.details.units': 'Unités', 'ui.details.intel': 'Case / unité', 'ui.details.log': 'Événements',
    'ui.dialog.confirm': 'Confirmer', 'ui.dialog.cancel': 'Annuler',
    'ui.dialog.leaveMission.body': 'La mission en cours se termine. Les ordres et la progression sont perdus. Le choix de mission s’ouvre ensuite.',
  },
};

export function createShellText(language) {
  return (key, params = {}) => {
    const localized = language.t(key, params);
    if (localized !== key) return localized;
    const provisional = navigation[language.current]?.[key] ?? navigation.de[key];
    if (provisional) return provisional.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
    return localized;
  };
}
